spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: -1
#mongodbde连接信息
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: admin
      username: admin
      password: qiaoweitong




